### PR TITLE
Updating Cucumber dependency.

### PR DESCRIPTION
**Pull request by jimCresswell**
Hello @vgamula ,

I'd like to update the version of Cucumber used please.

And also end the stream on scenario failure so that subsequent Gulp tasks will execute properly.

### CODE REVIEW

**Comment by sponte** [comment]
:+1:

**Comment by vgamula** [comment]
Hi! 
Thanks!

**Comment by vgamula** [comment]
v0.0.12 is already in NPM

**Comment by jimCresswell** [comment]
Awesome, thanks!

**Pull request merged**
