### PR TITLE
Update to cucumber ^3.0.0

### PR DESCRIPTION
**Pull request by u9520107**
@vgamula Recently I've been trying to use cucumber with my projects together with gulp-istanbul, and found that this lib is still using cucumber 1.x.x. So I upgrade all the dependencies to the latest versions and modified the tags implementation to go along with cucumber 3.x.
Can you please take a look?
If things are ok, please help bump npm version and release it?

Thanks!

### CODE REVIEW

**Comment by vgamula** [comment]
Hello, @u9520107! Thank you for this huge work!

**Comment by vgamula** [comment]
Bumped version v0.0.23 with all your fixes. Thank you!

**Comment by pmosconi** [comment]
Thank you very much for the update: I confirm everything is now working.
There is a minor inconsistency on readme line 39 because cucumber 3 among other things changed format options: pretty doesn't exist any more and the default is now progress, it looks like there are more formats too.

Thanks again.

**Comment by vgamula** [comment]
@pmosconi cool, thanks, I will update readme today/tomorrow.

**Pull request merged**
